; Copyright © Microsoft Corp.

[Theme]
; Windows - IDS_THEME_DISPLAYNAME_AERO_LIGHT
DisplayName=regular
ThemeId={AD570B29-F72A-4AC4-A2E7-0ED092F0D6D7}

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Cursors]
AppStarting=
Arrow=%SystemRoot%\Cursors\W11_light_v2.2\pointer.cur
Crosshair=%SystemRoot%\Cursors\W11_light_v2.2\precision.cur
Hand=
Help=%SystemRoot%\Cursors\W11_light_v2.2\help.cur
IBeam=%SystemRoot%\Cursors\W11_light_v2.2\beam.cur
No=%SystemRoot%\Cursors\W11_light_v2.2\unavailable.cur
NWPen=%SystemRoot%\Cursors\W11_light_v2.2\handwriting.cur
SizeAll=
SizeNESW=%SystemRoot%\Cursors\W11_light_v2.2\dgn2.cur
SizeNS=%SystemRoot%\Cursors\W11_light_v2.2\vert.cur
SizeNWSE=%SystemRoot%\Cursors\W11_light_v2.2\dgn1.cur
SizeWE=%SystemRoot%\Cursors\W11_light_v2.2\horz.cur
UpArrow=%SystemRoot%\Cursors\W11_light_v2.2\alternate.cur
Wait=
DefaultValue=macxwin

[Control Panel\Desktop]
Wallpaper=E:\Personal\Github\lazywin\wallpapers\8.jpg
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC4567C73
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@mmres.dll,-800

[Slideshow]
ImagesRootPIDL=mIAFA8BUg/E0gouOpBhoYjAArADMdmBAvUkOcBAAAAAAAAAAAAAAAAAAAAAAAAgWAEDAAAAAAw5Vh5ZEgAVZyN3buFGbAAgQAkAAEAw7+yoVbgpIYhkMuAAAA0DAAAAAAUDAAAAAAAAAAAAAAAAAAAgSoAFAQBQZAIHAzBwbA4GAhBAbAAAAYAAVAEDAAAAAAICWckDEgcUa0hWdiBAA+AQCAQAAv7rWXZPTigFH54CAAAA1AAAAAAgAAAAAAAAAAAAAAAAAAAAAUpTTAcEApBAdAgGA1BgYAAAAWAgVAEDAAAAAAICWvjDEgwWY6l3dp5GAABQCAQAAv7rIYliNig1744CAAAgv5AAAAAQAAAAAAAAAAAAAAAAAAAAAOsj/AwGAhBgeAkHA3BQaA4GAAAgFAMPAxAAAAAAAigF/4ABI3FGbsBXYwVmczBAAGBQCAQAAv7rIY1OOigVO54CAAAwH6AAAAAQAAAAAAAAAAAAAAAAAAAAAoyNBAcHAhBAbAwGAwBQYAAHAlBgcAMHAAAgGAMJAAAwJA8uvFCAAAEzUQN1td66/Nyx/DFIjECkOjOXLpBAAAQGAAAAAfAAAAwCAAAwdAkGAuBAZA8GA3BwcA4CApBQbA0GAlBgcAMHApBgdAUGAjBwbA4GA0BgcA8GAsBAcAEGAuBQZAwGAfBwYAcHA1AgbAEDAoBgMAQHA4BQeAUGA3BQeAAAAAAAAAAAAAAgGAAAA

Interval=60000
Shuffle=1
